services:
  mysql:
    image: mysql:9.4
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      # MYSQL_DATABASE: main
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "127.0.0.1:3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    platform: linux/amd64
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - mysql
